blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from post.views import registration, edit

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from post import views
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls')),
    url(r'^resume/$', TemplateView.as_view(template_name='resume/index.html'),name='resume_cv'),
]

urlpatterns += [
    url(r'^$', RedirectView.as_view(url="/post/list", permanent=True)),
]

urlpatterns +=[
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns +=[
    url(r'^accounts/edit/$', edit, name='account_edit' ),
]

#user registration
urlpatterns +=[
    url(r'^registration/$', registration, name='registration')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from . import views

app_name = 'post'

urlpatterns = [
    url(r'^list', views.PostList.as_view(), name='lists'),
    
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/'\
    r'(?P<post>[-\w]+)/$', views.detail, name='post_detail'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/'\
    r'(?P<post>[-\w]+)/delete/$', views.delete, name='post_delete'),

    url(r'^create/$', views.post_create, name="post_create"),

    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/'\
    r'(?P<post>[-\w]+)/update/$', views.post_update, name='post_update'), 

    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),

    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from django.core.urlresolvers import reverse

#taggit 
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

# Create your models here.
def upload_location(instance, filename):
    return "%s %s"%(instance.id, filename)


class PostManager(models.Manager):
    def get_queryset(self):
        pubquery = super(PostManager, self).get_queryset()
        query = pubquery.filter(status='published').filter(publish__lte=timezone.now())
        return query

class Post(models.Model):
    STATUS_CHOICE = (
       ('draft', 'Draft'), 
       ('published', 'Published')
    )
    title    = models.CharField(max_length=50)
    slug     = models.SlugField(max_length=250 , unique_for_date='publish')
    author   = models.ForeignKey(User, related_name='blog_post')
    image = models.ImageField(upload_to=upload_location,
                                null=True,
                                blank=True,
                                height_field = 'height_field',
                                width_field = 'width_field',
                                )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    image_info = models.CharField(max_length=30, default='image info', null=True, blank=True)
    content  = models.TextField()

    publish  = models.DateTimeField(default=timezone.now)
    created  = models.DateTimeField(auto_now=True)
    updated  = models.DateTimeField(auto_now_add=True)
    status   = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
    objects = models.Manager()
    tags = TaggableManager()
    publishs = PostManager()

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail', args=[self.publish.year,
                                 self.publish.month,                             
                                 self.publish.day,
                                 self.slug])
    
    def late_post(self):
        #get late post that are after the timezone
        return self.created < self.publish

    def early_post(self):
        #get early post that are before the timezone
        return self.created > self.publish
                                 
from django.db.models.signals import pre_save
from django.utils.text import slugify
  
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug
         
def pre_save_post_reciver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_reciver, sender=Post)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to=upload_location, blank=True, null=True)

    def __str__(self):
        return 'profile for user {}'.format(self.user.username)

post/forms.py
from django import forms
from django.contrib.auth.models import User
from pagedown.widgets import PagedownWidget

from .models import Post, Profile


class PostForm(forms.ModelForm):
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "image_info",
            "author",
            "content",
            "tags",
            "publish",
            "status"
        ]

class PostEmail(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False,
    widget=forms.Textarea)

class ResumeMail(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=False, help_text="optional")
    last_name = forms.CharField(max_length=20, required=False, help_text='optional')
    email     = forms.EmailField(max_length=200, help_text="Required, use a valid email")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
'''
from django.contrib.auth.models import User
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password",
                            widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat Password",
                            widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('password don\'t match')
        return cd['password2']'''

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

post/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, Http404,redirect, HttpResponseRedirect
from django.views.generic import ListView
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.contrib.auth.decorators import login_required
from django.db.models import Q


from . models import Post
from .models import Profile
from . forms import PostForm, PostEmail, UserRegistrationForm, UserEditForm, ProfileEditForm

class PostList(ListView):
    model = Post
    paginate_by = 5
    context_object_name = 'posts'
    def get_queryset(self):
        post_list = Post.publishs.all()
        if self.request.user.is_superuser or self.request.user.is_staff:
            post_list = Post.objects.all()
        return post_list
    template_name = 'post/list.html'


def detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug = post,
                                    publish__year=year,
                                    publish__month = month,
                                    publish__day = day)
    print(post)
    context = {
        'post':post,
        'title': post.slug
    }
    return render(request, 'post/detail.html', context)

def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        messages.success(request, "post succesfully created")
        return HttpResponseRedirect(post.get_absolute_url())
    context = {
        'form':form
    }
    return render(request, 'post/post_form.html', context)

def delete(request, year, month, day, post):
    post = get_object_or_404(Post, slug = post,
                                    publish__year=year,
                                    publish__month = month,
                                    publish__day = day)
    post.delete()
    messages.success(request, 'successfully deleted')
    return redirect('post:lists')

def post_update(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                    publish__year = year,
                                    publish__month = month,
                                    publish__day = day)
    form = PostForm(request.POST or None,request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        messages.success(request, "successfully updated")
        return HttpResponseRedirect(post.get_absolute_url())
    context = {
        'title':post.title,
        "post":post,
        "form":form
    }
    return render(request, 'post/post_form.html', context)

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == Post:
        form = PostEmail(request.Post)
        if form.is_valid():
            cd = form.cleaned_data
            post_uri = request.build_absolute_uri(post.get.
                get_absolute_url())
            subject = "{} ({}) recommends you reading {}".format(cd['name'], cd['email'],post.title)
            message = "Read {} at {}/n/n{}\'s comments:{}".format(
                post.title, post_uri,cd['name'],cd['comment']
            )
            send_mail(subject, message, akubosylvernus@gmail.com, [cd['to']])
            sent = True
    else:
        form = PostEmail()
    context = {
        'post':post,
        'form':form,
        'sent':sent,    }
    return render(request, 'post/form.html', context)

def post_list(request, tag_slug=None):
    post_list = Post.publishs.all()
    if request.user.is_staff or request.user.is_superuser:
        post_list = Post.objects.all()
    if tag_slug:
        tag = get_object_or_404(Tag, tag_slug)
        post_list = post_list.filter(Tags__in[tag])
    query = request.GET.get("q")
    if query:
        post_list = post_list.filter(
            Q(title__icontains=query)|
            Q(username__icontains=query)|
            Q(content__icontains=query)).distinct()
    paginator = Paginator(post_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
       # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
       # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'post/list.html', locals())



'''
def registration(request):
    if request.method == 'Post':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # set the given password
            new_user.set_password(user_form.cleaned_data['password'])
            # save the user object
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request, 'register_done.html', {'new_user': new_user})
    else:
            user_form = UserRegistrationForm()
    return render(request, 'register.html', {'user_form': user_form})'''
    
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms  import UserCreationForm

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            profile = Profile.objects.create(user=user)
            login(request, user)
            return redirect('/')
    else:
        form = UserRegistrationForm()
    return render(request, 'register.html', {'form': form})

@login_required
def edit(request):
    if request.method == 'Post':
        user_form = UserEditForm(instance=request.user,
                                data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                        data=request.POST,
                                        files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success("profile updated successfuly")
        else:
            messages.error("profile update failed")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    context = {
        'user_form':user_form,
        'profile_form':profile_form,
    }
    return render(request,'registration/edit.html', context)
    

post/templates/post/base.html
<! DOCTYPE html>
<html lang="eng">
{% load static %}
{% load crispy_forms_tags %}
<head>
    <title>{% block title %}silva blog{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<body>
    	{% include "post/message.html" %}
    <nav class="navbar navbar-inverse" >
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'post:lists' %}" class="navbar-brand" ><img alt="silvablog" class="pull-left" style="max-height:40px;margin-top: -10px" src="{% static 'image\construct.jpg' %}" /> </a>
            </div>
            <div class="collapse navbar-collapse" id="mynavbar">
                    <form class="navbar-form navbar-left" method="GET">
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="search post" name="q" value="{{ request.Get.q }}">
                          <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                              <i class="glyphicon glyphicon-search"></i>
                            </button>
                          </div>
                        </div>
                      </form>
                <ul class="nav navbar-nav">
                    <li class="navlist"><a href="{% url 'post:lists' %}">Home</a></li>
                    <li class="navlist"><a href="{% url 'resume_cv' %}">Resume</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><img class="img-responsive" style="border-radius:50%;max-height:20px;" src="{% static 'image\construct.jpg' %}" alt="ini"><span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li style="border-bottom: solid black 2px;background-color:#888">logged in as {{ user.get_username }}</li>
                                    <li><a href="{% url 'account_edit' %}">profile</a></li>
                                    <li><a href="{% url 'logout' %}?=next{{request.path}}">logout</a></li>
                                </ul>
                            </li>
                     {% else %}
                        <li ><a href="{% url 'registration' %}"><span class="glyphicon glyphicon-user"><span class="navlist" style="margin-left: 5px;">Signup</span></span></a></li> or
                        <li ><a href="{% url 'login' %}?=next{{request.path}}"><span class="glyphicon glyphicon-log-in"><span class="navlist" style="margin-left: 5px;">Login</span></span></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></Script>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=956538567820660";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
<div>    
    {% block content %}
	{% endblock %}
</div>
<footer class="containers " style="margin-top: 200px;">
	<div class="footer-copyright"><b>django</b> web app<br>  © All rights reserved.</div>
</footer>
</body>
</html>

post/templates/post/detail.html
{% extends "post/base.html" %}

{% block title %}{{ post.title }} || {{ block.super }} {% endblock %}

{% block content %}


<!--
<p>
	<a href="{% url 'post:post_share' post.id %}">    
		Share this post  
	</a>
</p>
-->

<div style="border-top: solid #424242 8px ; margin: 10px 24px 0px;
">

<div style="padding-top: 50px;" class="head">
	<h2 style="text-transform: uppercase;font-weight: 700">{{ post.title }}</h2>

	<p style="color: #777;">{{ post.created|date }}</p>
	
	
	<p style="color:#777;font-size:20px;" class="glyphicon glyphicon-user" ><span style="font-family:sans-serif">{{ post.author }}</span>  </p>   
	{% if post.tags %}
		<p style="color:#777;font-size:20px;" class="glyphicon glyphicon-tags" >
			<span style="font-family:sans-serif">{{ post.tags.all|join:", "}}</span>
		</p> 
	{% endif %}
	
	{% if post.status == 'draft' %}
		<p style="color: red">Draft←future post</p>
	{% endif %}

	<div class="d">
		<a href="http://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" class="fa fa-facebook"></a>
		<a href="https://twitter.com/home?status={{ instance.content}}%20{{ request.build_absolute_uri }}" class="fa fa-twitter"></a>
		<a class="fa fa-linkedin" href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}/&title={{ instance.title }}&summary={{ quote_tag }}&source={{ request.build_absolute_uri }}/"></a>
		<a class="fa fa-google" href="https://plus.google.com/share?url={{ request.build_absolute_uri }}">+</a>
		<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}/&title={{ instance.title }}"></a>
	</div>
</div>

<div style=" padding-top: 10px; padding-bottom: 10px; margin-bottom: 300px;width: 100%">
			{% if post.image %}
				<img style="box-shadow:1px 2px 30px; max-height: 600px " class="img-responsive" alt="{{ post.image_info }}" width="100%"  src="{{ post.image.url }}" />
			{% endif %}
			
			<div class="content-text">{{ post.content|safe }}</div>

			<!-- facebook comment plugin-->
			<div class="fb-comments"  data-width="100%" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
		</div>
	</div>
</div>

</div>
{% endblock %}

post/templates/post/form.html
{% extends "post/base.html" %}


{% block title %}
    share a post
{% endblock title %}
    

{% block content %}
{% if sent %}    
    <h1>E-mail successfully sent</h1>    
    <p>      
        "{{ post.title }}" was successfully sent to {{ cd.to }}.    
    </p>  
{% else %}    
    <h1>Share "{{ post.title }}" by e-mail</h1>    
    <form action="." method="post">      
        {{ form|crispy }}      
        {% csrf_token %}      
        <input type="submit" value="Send e-mail">    
    </form>  
{% endif %}

{% endblock %}

post/templates/post/list.html
{% extends 'post/base.html' %}
{% block title %}{{ super.block }}{% endblock %}
{% block content %}
{% load static %}

<header class=" con-img" style="margin-top:20px;" >
		<img class="img-responsive"  src="{% static 'image\head.jpg'' %}" alt="image header">
		<p class="con-text" style="font-weight: 900;color: #424242; ">SILVA BLOG</p>
		<P class="con-bottom" style="text-transform: uppercase; ">python django developer</P>
</header>



<div class="head" style="border-top: solid #424242 8px; text-align: left; margin: 0px 24px 0px; mar
">
	<div style="padding-top: 50px">
	{% for post in posts %}

	<div style=" border-bottom: solid #424242 2px; 	font-family: "Open Sans", arial, sans-serif;" class="post-list" >
	    <ul style="list-style: none">
		        <li>
		        	<h3>
		        	<a href="{{ post.get_absolute_url }}">{{ post.title}} / 
		        		<span style="text-transform: lowercase; font-weight: 100">Published {{ post.created|date}}
		        		</span>
		        	</a>
		       </h3>
		        </li>
		    </ul>
		</div>
		{% endfor %}
		</div>
	</div>
<div style="margin-top: 50px; margin-bottom: 300px;" class="paginator head">
{% include "post/pagination.html" %}
</div>
{% endblock %}

post/templates/post/message.html
{% if messages %}
    <div class="messages" style="background-color: 
    rgba(255,0,0,1.0);display: block; text-align: center;color: white">
        <ul class="messages" style="list-style: none;">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {% if 'html_safe' in message.tags %}{{ message|safe }}{% else %}{{ message}}{% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

post/templates/post/pagination.html
{% if  is_paginated %}
<div class="pagination">  
    <span class="step-links">    
        {% if page_obj.has_previous %}      
        <a href="?page={{ page_obj.previous_page_number }}">←Previous</a>    
        {% endif %}    
    
        {% if page_obj.has_next  %}        
        <a href="?page={{ page_obj.next_page_number }}">Next→</a>      
        {% endif %}  
    </span> 
</div>
{% endif %}

post/templates/post/post_form.html
{% extends "post/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="col-md-12 col-md-offset-12" style="border-top: solid #424242 8px ; margin: 20px 24px 0px;">

	<div style="margin-top: 50px">
		<h2>post form</h2>
		<form method="POST" action="" enctype="multipart/form-data">
		    {% csrf_token %}
			{{ form|crispy }}
			<div class="contact-form form-group">
				<input type="submit" class="contact-form form-input" style="width: 100%;" value="create post"/>
				</div>
		</form>
	</div>


</div>

{% endblock %}